package com.mansouri.customsduty;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import android.text.*;import org.json.JSONObject;import java.io.*;import java.net.*;import java.text.*;import java.util.*;

public class CurrencyCalculatorActivity extends Activity {
 final String[] names={"دلار آمریکا","یورو","درهم امارات","یوان چین","ین ژاپن","منات آذربایجان","ریال عمان","لیر ترکیه","روبل روسیه","دینار عراق","روپیه پاکستان","روپیه هند","فرانک سوییس","دینار کویت"};
 final String[] codes={"USD","EUR","AED","CNY","JPY","AZN","OMR","TRY","RUB","IQD","PKR","INR","CHF","KWD"};
 final double[] customs={1310661d,1551964d,356885d,188931d,8452.85d,770852d,3407574d,30114d,17113d,999.56d,4685.88d,14386d,1691667d,4272304d};
 final String[] flags={"🇺🇸","🇪🇺","🇦🇪","🇨🇳","🇯🇵","🇦🇿","🇴🇲","🇹🇷","🇷🇺","🇮🇶","🇵🇰","🇮🇳","🇨🇭","🇰🇼"};
 final int blue=Color.rgb(13,71,161),dark=Color.rgb(18,32,56),page=Color.rgb(246,248,252),green=Color.rgb(20,120,85);
 Spinner from,to;EditText amount;TextView result,fromFlag,toFlag,rateInfo,status;Switch onlineSwitch;HashMap<String,Double> onlineRates=new HashMap<>();boolean onlineReady=false;
 @Override public void onCreate(Bundle b){super.onCreate(b);build();}
 GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}
 TextView tv(String s,int n){TextView t=new TextView(this);t.setText(s);t.setTextSize(n);t.setTextColor(dark);t.setPadding(12,6,12,6);return t;}
 void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(14,14,14,24);root.setBackgroundColor(page);
  TextView h=tv("ماشین حساب ارز",22);h.setTextColor(Color.WHITE);h.setGravity(Gravity.CENTER);h.setTypeface(null,Typeface.BOLD);h.setBackground(bg(blue,24));root.addView(h,new LinearLayout.LayoutParams(-1,70));
  LinearLayout mode=new LinearLayout(this);mode.setGravity(Gravity.CENTER_VERTICAL);TextView ml=tv("نوع نرخ",15);ml.setTypeface(null,Typeface.BOLD);onlineSwitch=new Switch(this);onlineSwitch.setText("🌐 نرخ آنلاین جهانی");onlineSwitch.setTextSize(15);onlineSwitch.setChecked(false);mode.addView(ml,new LinearLayout.LayoutParams(0,60,1));mode.addView(onlineSwitch);root.addView(mode);
  root.addView(makeBox(true),new LinearLayout.LayoutParams(-1,78));LinearLayout swr=new LinearLayout(this);swr.setGravity(Gravity.CENTER);Button sw=new Button(this);sw.setText("⇅");sw.setTextSize(20);sw.setAllCaps(false);sw.setTextColor(Color.WHITE);sw.setBackground(bg(blue,30));sw.setOnClickListener(v->{int p=from.getSelectedItemPosition();from.setSelection(to.getSelectedItemPosition());to.setSelection(p);update();});swr.addView(sw,new LinearLayout.LayoutParams(60,52));root.addView(swr,new LinearLayout.LayoutParams(-1,58));root.addView(makeBox(false),new LinearLayout.LayoutParams(-1,78));
  rateInfo=tv("1 USD = 1 USD",14);rateInfo.setTextColor(blue);rateInfo.setGravity(Gravity.CENTER);status=tv("🏛 استفاده از نرخ گمرکی برنامه",13);status.setTextColor(green);status.setGravity(Gravity.CENTER);root.addView(rateInfo);root.addView(status);
  Button refresh=new Button(this);refresh.setText("🔄 بروزرسانی نرخ آنلاین");refresh.setAllCaps(false);refresh.setOnClickListener(v->fetch());root.addView(refresh,new LinearLayout.LayoutParams(-1,52));setContentView(root);
  AdapterView.OnItemSelectedListener li=new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int x,long id){update();setFlags();}};from.setOnItemSelectedListener(li);to.setOnItemSelectedListener(li);amount.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){update();}public void afterTextChanged(Editable e){}});onlineSwitch.setOnCheckedChangeListener((v,c)->{if(c)fetch();else{onlineReady=false;status.setText("🏛 استفاده از نرخ گمرکی برنامه");update();}});update();setFlags();}
 LinearLayout makeBox(boolean source){LinearLayout box=new LinearLayout(this);box.setGravity(Gravity.CENTER_VERTICAL);box.setPadding(8,5,8,5);box.setBackground(bg(Color.WHITE,18));
  LinearLayout content=new LinearLayout(this);content.setGravity(Gravity.CENTER_VERTICAL);content.setOrientation(LinearLayout.HORIZONTAL);
  if(source){amount=new EditText(this);amount.setText("1");amount.setTextSize(20);amount.setGravity(Gravity.CENTER);amount.setInputType(2|8192);amount.setSingleLine(true);amount.setBackground(bg(page,14));content.addView(amount,new LinearLayout.LayoutParams(0,58,1));fromFlag=tv(flags[0],27);fromFlag.setGravity(Gravity.CENTER);content.addView(fromFlag,new LinearLayout.LayoutParams(58,58));}
  else {result=tv("0",20);result.setTextColor(green);result.setGravity(Gravity.CENTER);result.setTypeface(null,Typeface.BOLD);result.setBackground(bg(Color.rgb(232,248,241),14));content.addView(result,new LinearLayout.LayoutParams(0,58,1));toFlag=tv(flags[3],27);toFlag.setGravity(Gravity.CENTER);content.addView(toFlag,new LinearLayout.LayoutParams(58,58));}
  box.addView(content,new LinearLayout.LayoutParams(-1,-1));TextView label=tv(source?"دلار آمریکا":"یوان چین",13);label.setVisibility(View.GONE);box.setTag(source);return wrapWithName(box,source);}
 LinearLayout wrapWithName(LinearLayout box,boolean source){LinearLayout outer=new LinearLayout(this);outer.setOrientation(LinearLayout.VERTICAL);TextView name=tv(source?names[0]:names[3],13);name.setGravity(Gravity.CENTER);name.setTypeface(null,Typeface.BOLD);outer.addView(name,new LinearLayout.LayoutParams(-1,30));outer.addView(box,new LinearLayout.LayoutParams(-1,78));box.setOnClickListener(v->showCurrencyDialog(source));if(source)fromFlag.setOnClickListener(v->showCurrencyDialog(true));else toFlag.setOnClickListener(v->showCurrencyDialog(false));return outer;}
 void showCurrencyDialog(boolean source){final Spinner sp=new Spinner(this);sp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,names));sp.setSelection(source?from.getSelectedItemPosition():to.getSelectedItemPosition());new AlertDialog.Builder(this).setTitle(source?"انتخاب ارز مبدأ":"انتخاب ارز مقصد").setView(sp).setPositiveButton("تأیید",(d,w)->{if(source)from.setSelection(sp.getSelectedItemPosition());else to.setSelection(sp.getSelectedItemPosition());setFlags();update();}).setNegativeButton("لغو",null).show();}
 void setFlags(){if(fromFlag!=null)fromFlag.setText(flags[from.getSelectedItemPosition()]);if(toFlag!=null)toFlag.setText(flags[to.getSelectedItemPosition()]);}
 double rate(){int a=from.getSelectedItemPosition(),b=to.getSelectedItemPosition();if(a==b)return 1;if(onlineSwitch.isChecked()&&onlineReady)return onlineRates.get(codes[b])/onlineRates.get(codes[a]);return customs[a]/customs[b];}
 void update(){if(result==null)return;double a=0;try{a=Double.parseDouble(amount.getText().toString().replace(",",""));}catch(Exception e){}double r=rate();result.setText(fmt(a*r));rateInfo.setText("1 "+codes[from.getSelectedItemPosition()]+" = "+fmtRate(r)+" "+codes[to.getSelectedItemPosition()]);}
 String fmt(double x){return new DecimalFormat("#,##0.####").format(x);}String fmtRate(double x){return new DecimalFormat("#,##0.####").format(x);}
 void fetch(){status.setText("🌐 دریافت آخرین نرخ آنلاین...");new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL("https://open.er-api.com/v6/latest/USD").openConnection();c.setConnectTimeout(10000);c.setReadTimeout(10000);BufferedReader br=new BufferedReader(new InputStreamReader(c.getInputStream()));StringBuilder s=new StringBuilder();String q;while((q=br.readLine())!=null)s.append(q);JSONObject rates=new JSONObject(s.toString()).getJSONObject("rates");HashMap<String,Double> tmp=new HashMap<>();for(String x:codes)tmp.put(x,rates.getDouble(x));onlineRates=tmp;onlineReady=true;runOnUiThread(()->{status.setText("🌐 آخرین نرخ آنلاین دریافت شد • "+new SimpleDateFormat("yyyy/MM/dd HH:mm",Locale.US).format(new Date()));update();});}catch(Exception e){onlineReady=false;runOnUiThread(()->{status.setText("⚠ دریافت نرخ آنلاین ناموفق بود؛ نرخ گمرکی فعال ماند");update();});}}).start();}
}
