package com.mansouri.customsduty;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.view.*;
import android.widget.*;
import java.text.DecimalFormat;
import java.util.*;

public class MainActivity extends Activity {
    LinearLayout root, form, resultBox;
    Spinner currency, term;
    EditText name, tariff, buy, duty, otherDuty, transportFromValuePercent, insuranceFromValue, transportCost, insuranceCost;
    TextView rate, total;
    Switch valueCostSwitch;
    final String[] currencies={"دلار آمریکا","یورو","درهم امارات","یوان چین","ین ژاپن","منات آذربایجان","ریال عمان","لیر ترکیه","روبل روسیه","دینار عراق","روپیه پاکستان","روپیه هند","فرانک سوییس","دینار کویت"};
    final String[] terms={"EXW","FCA","FAS","FOB","CPT","CFR","DDU","DDP","DAP","DPU","CIP","CIF"};
    final Map<String,Double> customsRates=new LinkedHashMap<>();
    final int blue=Color.rgb(13,71,161), dark=Color.rgb(18,32,56), page=Color.rgb(246,248,252), green=Color.rgb(20,120,85), inactive=Color.rgb(232,235,240);

    @Override public void onCreate(Bundle b){super.onCreate(b);
        customsRates.put("دلار آمریکا",1310661d); customsRates.put("یورو",1551964d); customsRates.put("درهم امارات",356885d); customsRates.put("یوان چین",188931d); customsRates.put("ین ژاپن",8452.85); customsRates.put("منات آذربایجان",770852d); customsRates.put("ریال عمان",3407574d); customsRates.put("لیر ترکیه",30114d); customsRates.put("روبل روسیه",17113d); customsRates.put("دینار عراق",999.56); customsRates.put("روپیه پاکستان",4685.88d); customsRates.put("روپیه هند",14386d); customsRates.put("فرانک سوییس",1691667d); customsRates.put("دینار کویت",4272304d);
        build();
    }
    TextView tv(String s,int sp){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(dark);t.setPadding(18,10,18,10);return t;}
    TextView title(String s){TextView t=tv(s,20);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setPadding(18,22,18,10);return t;}
    GradientDrawable box(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}
    EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(16);e.setGravity(Gravity.RIGHT);e.setSingleLine(true);e.setPadding(14,3,14,3);e.setTextColor(dark);e.setBackground(box(Color.WHITE,18));return e;}
    LinearLayout row(String label,EditText e){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);TextView l=tv(label,15);l.setTypeface(Typeface.DEFAULT,Typeface.BOLD);r.addView(l,new LinearLayout.LayoutParams(0,62,1));r.addView(e,new LinearLayout.LayoutParams(0,62,1));r.setPadding(4,3,4,3);return r;}
    LinearLayout rowSpinner(String label,Spinner s){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.addView(tv(label,15),new LinearLayout.LayoutParams(0,62,1));r.addView(s,new LinearLayout.LayoutParams(0,62,1));return r;}
    void build(){ScrollView sv=new ScrollView(this);sv.setFillViewport(true);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(12,0,12,28);root.setBackgroundColor(page);sv.addView(root);setContentView(sv);header();basic();costs();calcButton();results();about();}
    void header(){LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(8,18,8,18);h.setBackground(box(blue,28));TextView m=tv("☰",28);m.setTextColor(Color.WHITE);m.setGravity(Gravity.CENTER);m.setOnClickListener(v->showSettings());LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setGravity(Gravity.CENTER);TextView a=tv("H&M Customs",22);a.setTextColor(Color.WHITE);a.setTypeface(Typeface.DEFAULT,Typeface.BOLD);a.setGravity(Gravity.CENTER);TextView b=tv("محاسبه حقوق ورودی کالا",14);b.setTextColor(Color.WHITE);b.setGravity(Gravity.CENTER);c.addView(a);c.addView(b);TextView g=tv("⚙",24);g.setTextColor(Color.WHITE);g.setGravity(Gravity.CENTER);g.setOnClickListener(v->showSettings());h.addView(m,new LinearLayout.LayoutParams(55,80));h.addView(c,new LinearLayout.LayoutParams(0,80,1));h.addView(g,new LinearLayout.LayoutParams(55,80));root.addView(h);}
    void basic(){form=new LinearLayout(this);form.setOrientation(LinearLayout.VERTICAL);root.addView(title("اطلاعات کالا"));root.addView(form);name=input("مثال: تلفن همراه هوشمند");tariff=input("مثال: 8517131000");form.addView(row("نام کالا",name));form.addView(row("شماره تعرفه HS",tariff));currency=new Spinner(this);currency.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,currencies));form.addView(rowSpinner("ارز",currency));rate=tv("نرخ ارز گمرکی: "+fmt(customsRates.get(currencies[0]))+" ریال",14);rate.setTextColor(blue);form.addView(rate);currency.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int pos,long id){rate.setText("نرخ ارز گمرکی: "+fmt(customsRates.get(currencies[pos]))+" ریال");updateValueInsurance();}});term=new Spinner(this);term.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,terms));term.setSelection(4);term.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int pos,long id){updateTermCostFields();}});form.addView(rowSpinner("ترم تحویل",term));}
    void costs(){root.addView(title("هزینه‌ها و حقوق ورودی"));buy=input("مبلغ به ارز انتخابی");duty=input("مثلاً 5");otherDuty=input("0");transportFromValuePercent=input("0");insuranceFromValue=input("0");transportCost=input("1");insuranceCost=input("1");transportFromValuePercent.setEnabled(false);insuranceFromValue.setEnabled(false);transportFromValuePercent.setBackground(box(inactive,18));insuranceFromValue.setBackground(box(inactive,18));buy.setText("0");transportFromValuePercent.setText("0");insuranceFromValue.setText("0");otherDuty.setText("0");transportCost.setText("1");insuranceCost.setText("1");form.addView(row("مبلغ خرید",buy));form.addView(row("ماخذ حقوق ورودی (%)",duty));form.addView(row("سایر عوارض (%)",otherDuty));
        form.addView(row("هزینه حمل و نقل",transportCost));
        form.addView(row("هزینه بیمه",insuranceCost));
        LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);TextView label=tv("هزینه‌های محاسبه‌شده از ارزش کالا",16);label.setTypeface(Typeface.DEFAULT,Typeface.BOLD);valueCostSwitch=new Switch(this);valueCostSwitch.setText("خاموش");valueCostSwitch.setChecked(false);valueCostSwitch.setOnCheckedChangeListener((buttonView,isChecked)->setValueCostFields(isChecked));header.addView(label,new LinearLayout.LayoutParams(0,62,1));header.addView(valueCostSwitch,new LinearLayout.LayoutParams(-2,62));form.addView(header);
        form.addView(row("هزینه حمل از ارزش کالا",transportFromValuePercent));form.addView(row("هزینه بیمه از ارزش کالا",insuranceFromValue));
        buy.setOnFocusChangeListener((v,hasFocus)->{if(!hasFocus)updateValueInsurance();});
        updateTermCostFields();
    }
    boolean termHasDirectCosts(){if(term==null||term.getSelectedItem()==null)return false;String t=term.getSelectedItem().toString();return t.equals("EXW")||t.equals("FCA")||t.equals("FAS")||t.equals("FOB");}
    void updateTermCostFields(){boolean enabled=termHasDirectCosts();transportCost.setVisibility(enabled?View.VISIBLE:View.GONE);insuranceCost.setVisibility(enabled?View.VISIBLE:View.GONE);if(enabled){if(transportCost.getText().toString().trim().isEmpty())transportCost.setText("1");if(insuranceCost.getText().toString().trim().isEmpty())insuranceCost.setText("1");}else{transportCost.setText("0");insuranceCost.setText("0");}}
    void setValueCostFields(boolean enabled){valueCostSwitch.setText(enabled?"روشن":"خاموش");transportFromValuePercent.setEnabled(false);insuranceFromValue.setEnabled(false);transportFromValuePercent.setBackground(box(enabled?Color.WHITE:inactive,18));insuranceFromValue.setBackground(box(inactive,18));updateValueInsurance();}
    void updateValueInsurance(){if(transportFromValuePercent==null||insuranceFromValue==null)return;if(valueCostSwitch!=null&&!valueCostSwitch.isChecked()){transportFromValuePercent.setText("0");insuranceFromValue.setText("0");return;}double r=customsRates.get(currencies[currency.getSelectedItemPosition()]);double purchase=num(buy)*r;double freightFromValue=purchase*10.0/100.0;double insuranceValue=(purchase+freightFromValue)*5.0/1000.0;transportFromValuePercent.setText(fmt(freightFromValue));insuranceFromValue.setText(fmt(insuranceValue));}
    void calcButton(){Button b=new Button(this);b.setText("محاسبه حقوق ورودی  ▶");b.setTextSize(18);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackground(box(blue,20));b.setOnClickListener(v->calculate());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,65);p.setMargins(6,14,6,8);form.addView(b,p);}
    void results(){root.addView(title("نتیجه محاسبه"));resultBox=new LinearLayout(this);resultBox.setOrientation(LinearLayout.VERTICAL);resultBox.setPadding(16,16,16,16);resultBox.setBackground(box(Color.rgb(232,248,241),22));root.addView(resultBox);total=tv("مجموع حقوق ورودی: 0 ریال",20);total.setTextColor(green);total.setTypeface(Typeface.DEFAULT,Typeface.BOLD);resultBox.addView(total);}
    double num(EditText e){try{return Double.parseDouble(e.getText().toString().trim().replace(",",""));}catch(Exception x){return 0;}}
    void calculate(){double r=customsRates.get(currencies[currency.getSelectedItemPosition()]);double purchase=num(buy)*r;double termTransport=0;double termInsurance=0;if(termHasDirectCosts()){termTransport=num(transportCost)*r;termInsurance=num(insuranceCost)*r;}double valueTransport=0;double valueInsurance=0;if(valueCostSwitch!=null&&valueCostSwitch.isChecked()){valueTransport=purchase*10.0/100.0;valueInsurance=(purchase+valueTransport)*5.0/1000.0;}double cif=purchase+termTransport+termInsurance+valueTransport+valueInsurance;double d=cif*num(duty)/100.0;double vat=(cif+d)*10.0/100.0;double hilal=d*1.0/100.0;double waste=cif*5.0/10000.0;double twelve=cif*12.0/1000.0;double alih=(cif+d)*2.0/100.0;double other=cif*num(otherDuty)/100.0;double sum=d+vat+hilal+waste+twelve+alih+other;resultBox.removeAllViews();addResult("قیمت خرید",purchase);addResult("هزینه حمل و نقل",termTransport);addResult("هزینه بیمه",termInsurance);addResult("هزینه حمل از ارزش کالا",valueTransport);addResult("هزینه بیمه از ارزش کالا",valueInsurance);addResult("ارزش سیف",cif);addResult("حقوق ورودی",d);addResult("10% مالیات بر ارزش افزوده",vat);addResult("هلال احمر",hilal);addResult("پسماند",waste);addResult("دوازده در هزار",twelve);addResult("2% مالیات علی الحساب",alih);addResult("سایر عوارض",other);total=tv("مجموع حقوق ورودی: "+fmt(sum)+" ریال",20);total.setTextColor(green);total.setTypeface(Typeface.DEFAULT,Typeface.BOLD);resultBox.addView(total);}
    void addResult(String label,double value){resultBox.addView(tv(label+": "+fmt(value)+" ریال",16));}
    void about(){root.addView(title("درباره ما"));TextView a=tv("کارگزار رسمی گمرک\nترخیص انواع کالا از گمرک بازرگان و سایر گمرکهای شمال غربی\n\nحشمت اله منصوری\n09143612930",16);a.setBackground(box(Color.WHITE,22));a.setPadding(20,20,20,20);a.setOnClickListener(v->showAbout());root.addView(a);}
    void showAbout(){new AlertDialog.Builder(this).setTitle("H&M Customs").setMessage("کارگزار رسمی گمرک\n\nترخیص انواع کالا از گمرک بازرگان و سایر گمرکهای شمال غربی\n\nحشمت اله منصوری\n09143612930").setPositiveButton("تماس",(d,w)->{try{startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:09143612930")));}catch(Exception e){}}).setNegativeButton("بستن",null).show();}
    void showSettings(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(25,10,25,10);TextView a=tv("ℹ  درباره ما",18),reset=tv("↻  بازنشانی فرم",18);box.addView(a);box.addView(reset);AlertDialog d=new AlertDialog.Builder(this).setTitle("تنظیمات").setView(box).setNegativeButton("بستن",null).create();a.setOnClickListener(v->{d.dismiss();showAbout();});reset.setOnClickListener(v->{name.setText("");tariff.setText("");buy.setText("0");duty.setText("");otherDuty.setText("0");transportCost.setText("1");insuranceCost.setText("1");term.setSelection(4);valueCostSwitch.setChecked(false);valueCostSwitch.setText("خاموش");updateValueInsurance();updateTermCostFields();resultBox.removeAllViews();total=tv("مجموع حقوق ورودی: 0 ریال",20);total.setTextColor(green);resultBox.addView(total);d.dismiss();});d.show();}
    String fmt(double x){return new DecimalFormat("#,##0").format(Math.round(x));}
}
